name: Fetch Data, Build & Deploy Angular

on:
  workflow_dispatch:
    # You can also schedule it with cron if needed
    # - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout the repository ---
      - name: Checkout repo
        uses: actions/checkout@v3

      # --- Setup Python 3.11 ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- Install Python dependencies ---
      - name: Install Python dependencies
        run: pip install requests

      # --- Run Python script to fetch data & images ---
      - name: Fetch Sheet & Download Images
        run: |
          echo "Running Python script..."
          python scripts/fetch_data.py
        # The script should output to:
        # src/assets/data.json
        # src/assets/images/

      # --- Setup Node.js 22 for Angular ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # --- Install Angular dependencies ---
      - name: Install Angular dependencies
        run: npm install

      # --- Build Angular app for production ---
      - name: Build Angular App
        run: npm run build -- --configuration production --base-href /decor-rentals/ --verbose

      # --- Debug: List dist folder to confirm output ---
      - name: Debug dist folder
        run: ls -R dist/

      # --- Fix SPA routing for GitHub Pages ---
      - name: Fix SPA routing
        run: |
          if [ -f dist/decor-rentals/index.html ]; then
            cp dist/decor-rentals/index.html dist/decor-rentals/404.html
          else
            echo "index.html not found, aborting workflow"
            exit 1
          fi

      # --- Deploy to GitHub Pages ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/decor-rentals
